### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 127: invalid continuation byte

### ISSUE THREAD

**Issue by bbah123** [bio-phys/DiffusionGLS#1]
Hello ,
i am trying to run your code to calculate a diffusion coefficient from MD. I am getting this error when using one of the "example" .dat files as input:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 318, in main
    kernel.start()
  File "C:\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "C:\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
    self.asyncio_loop.run_forever()
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 538, in run_forever
    self._run_once()
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 1782, in _run_once
    handle._run()
  File "C:\Anaconda3\lib\asyncio\events.py", line 100, in _run
    self._loop.call_exception_handler(context)
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 1647, in call_exception_handler
    exc_info=True)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1514, in _log
    self.handle(record)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1594, in callHandlers
    lastResort.handle(record)
  File "C:\Anaconda3\lib\logging\__init__.py", line 894, in handle
    self.emit(record)
  File "C:\Anaconda3\lib\logging\__init__.py", line 1033, in emit
    self.handleError(record)
  File "C:\Anaconda3\lib\logging\__init__.py", line 947, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "C:\Anaconda3\lib\traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Anaconda3\lib\traceback.py", line 521, in __init__
    self._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 533, in _load_lines
    self.__context__._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 533, in _load_lines
    self.__context__._load_lines()
  File "C:\Anaconda3\lib\traceback.py", line 533, in _load_lines
    self.__context__._load_lines()
  [Previous line repeated 14 more times]
  File "C:\Anaconda3\lib\traceback.py", line 531, in _load_lines
    frame.line
  File "C:\Anaconda3\lib\traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Anaconda3\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Anaconda3\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Anaconda3\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 127: invalid continuation byte
```

I hope you can help me 
THANKS

**Comment by bbah123** [comment]
In Dfit.py line 3 :
# Jakob TomÃs Bullerjahn
This leads probably to my error

**Comment by sobuelow** [comment]
Sorry, I should probably check this page more often...
If you remove the Ã character, does the code work alright?
Best,
Soeren

**Comment by bbah123** [comment]
I copy pasted the code without the description and it is working.
